apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: rmyg3ev4d-nodejs 
  janus-idp.io/tekton: rmyg3ev4d-nodejs
  backstage.io/kubernetes-id: rmyg3ev4d-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rmyg3ev4d-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml