apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: rmyg3ev4d-nodejs
  janus-idp.io/tekton: rmyg3ev4d-nodejs
  backstage.io/kubernetes-id: rmyg3ev4d-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rmyg3ev4d-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
